-- liquibase formatted sql

-- changeset t.katkouski:1714074507425-1
CREATE TABLE cities
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    logo_id           UUID,
    country_entity_id BIGINT,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

-- changeset t.katkouski:1714074507425-2
CREATE TABLE countries
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

-- changeset t.katkouski:1714074507425-3
CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    password       VARCHAR(255),
    role       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset t.katkouski:1714074507425-4
ALTER TABLE cities
    ADD CONSTRAINT uc_cities_logo UNIQUE (logo_id);

-- changeset t.katkouski:1714074507425-5
ALTER TABLE countries
    ADD CONSTRAINT uc_countries_name UNIQUE (name);

-- changeset t.katkouski:1714074507425-6
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset t.katkouski:1714074507425-7
ALTER TABLE cities
    ADD CONSTRAINT unique_city_name_within_country UNIQUE (name, country_entity_id);

-- changeset t.katkouski:1714074507425-8
ALTER TABLE cities
    ADD CONSTRAINT FK_CITIES_ON_COUNTRY_ENTITY FOREIGN KEY (country_entity_id) REFERENCES countries (id);

-- changeset t.katkouski:1713887469988-9
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- changeset t.katkouski:1713887469988-10
INSERT INTO users (email, password, role, first_name, last_name)
VALUES
    ('admin@admin.com', crypt('admin', gen_salt('bf')), 'ADMIN', 'Admin', 'Adminov');

-- changeset t.katkouski:1713887469988-11
INSERT INTO users (email, password, role, first_name, last_name)
VALUES
    ('editor@editor.com', crypt('editor', gen_salt('bf')), 'EDITOR', 'Editor', 'Editorov');

